AWSTemplateFormatVersion: "2010-09-09"
Description: Install Docker and Docker Compose template
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Type: String
    Default: t2.micro
  Vpc:
    Type: AWS::EC2::VPC::Id

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8010
          ToPort: 8010
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8020
          ToPort: 8020
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8030
          ToPort: 8030
          CidrIp: 0.0.0.0/0
      VpcId: !Ref Vpc
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-09b42976632b27e9b
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData: # very important
        "Fn::Base64": !Sub |
          #!/bin/bash -ex
          /opt/aws/bin/cfn-init --stack ${AWS::StackName} --resource WebServer --configsets install-and-init --region ${AWS::Region}

    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          install-and-init:
            - install-packages
            - service-init
            - install-jenkins-docker
        install-packages:
          packages:
            yum:
              docker: []
              git: []

          commands:
            01-install-docker-compose:
              command: "pip install docker-compose"
              # test: "echo $(/usr/local/bin/docker-compose -v) > /tmp/docker_compose_version.txt"

        service-init:
          services:
            sysvinit:
              docker:
                enabled: true
                ensureRunning: true

        install-jenkins-docker:
          commands:
            01-prepare-jenkins-volume:
              command: "mkdir $HOME/jenkins_home"
            02-run-jenkins-container:
              command: "docker run -d -p 8010:8080 -v jenkins_home:/var/jenkins_home --name jenkins jenkins:2.60.1"

Outputs:
  jenkinsURL:
    Description: visit jenkins site over here
    Value: !Sub http://${WebServer.PublicDnsName}:8010
