AWSTemplateFormatVersion: "2010-09-09"
Description: WordPress single instance template
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Type: String
    Default: t2.micro
  Vpc:
    Type: AWS::EC2::VPC::Id
  DBName:
    Type: String
    Default: wordpressdb
  DBUser:
    Type: String
    Default: dbAdmin
  DBPassword:
    Type: String
    Default: passw0rd
    NoEcho: true
  DBClass:
    Type: String
    Default: db.t2.small
  DBAllocatedStorage:
    Type: Number
    Default: 5
    MinValue: 5
    MaxValue: 1024
  BlogTitle:
    Type: String
    Default: WP with pre-installed plugins
  BlogAdminUsername:
    Type: String
    Default: admin
  BlogAdminPassword:
    Type: String
    NoEcho: true
    Default: passw0rd
  BlogAdminEMail:
    Type: String
    Default: admin@example.com

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref Vpc
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-09b42976632b27e9b
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData: # very important
        "Fn::Base64": !Sub |
          #!/bin/bash -ex
          /opt/aws/bin/cfn-init --stack ${AWS::StackName} --resource WebServer --configsets install-and-init --region ${AWS::Region}

    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          install-and-init:
            - install-packages
            - service-config
            - service-init
            - configure-services
            - create-wp-cli-script
        install-packages:
          packages:
            yum:
              httpd: []
              php: []
              mysql: []
              php-mysql: []

          sources:
            /var/www/html: "http://wordpress.org/latest.tar.gz"
        service-config:
          files:
            "/tmp/create-wp-config":
              content: !Sub |
                #!/bin/bash -ex
                cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
                sed -i 's/database_name_here/${DBName}/g' /var/www/html/wordpress/wp-config.php
                sed -i 's/username_here/${DBUser}/g' /var/www/html/wordpress/wp-config.php
                sed -i 's/password_here/${DBPassword}/g' /var/www/html/wordpress/wp-config.php
                sed -i 's/localhost/${DBInstance.Endpoint.Address}/g' /var/www/html/wordpress/wp-config.php
              mode: 000500
              owner: root
              group: root
        service-init:
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true

        configure-services:
          commands:
            01_configure_wordpress:
              command: "/tmp/create-wp-config"

        create-wp-cli-script:
          files:
            "/tmp/install-wp-cli":
              content: !Sub |
                #!/bin/bash -ex
                cd /var/www/html/wordpress/wp-content/plugins

                wget -q -T 60 https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

                chmod +x wp-cli.phar
                mv wp-cli.phar /usr/local/bin/wp

                #Must setup WordPress and create admin user and password first before running the following plugin install
                wp core install --url='http://<PublicDnsName>/wordpress/wp-admin/install.php' --title='${BlogTitle}' --admin_user='${BlogAdminUsername}' --admin_password='${BlogAdminPassword}' --admin_email='${BlogAdminEMail}' --skip-email --allow-root
                      
                wp plugin install user-switching --activate --allow-root
                wp plugin install contact-form-7 --activate --allow-root
                wp plugin install duplicate-page --activate --allow-root
                wp plugin install enable-media-replace --activate --allow-root
                wp plugin install post-tags-and-categories-for-pages --activate --allow-root
                wp plugin install redirection --activate --allow-root
                wp plugin install relevanssi --activate --allow-root
                wp plugin install wp-extra-file-types --activate --allow-root
                #so many WPBakery Page Builder plugins. Need to be more specific
                #wp plugin install wpbakery-page-builder --activate --allow-root
                #Slider Revolution plugin does not exist
                #wp plugin install slider-revolution --activate --allow-root

              mode: 000500
              owner: root
              group: root

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open database for access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      VpcId: !Ref Vpc
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: MySQL
      DBName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: !Ref DBClass
      AllocatedStorage: !Ref DBAllocatedStorage
      VPCSecurityGroups:
        - !Ref DBSecurityGroup

Outputs:
  WebsiteURL:
    Description: WordPress website url
    Value: !Sub http://${WebServer.PublicDnsName}/wordpress
